// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDteXisIvCpKJUv_2MdcnzVyXtEyjHAUHQ',
    appId: '1:291924435034:web:4fe12557a6abb8943f3863',
    messagingSenderId: '291924435034',
    projectId: 'kadike',
    authDomain: 'kadike.firebaseapp.com',
    storageBucket: 'kadike.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWlzScv9XlnCsdxstOvPIbaNyhTHIjvg',
    appId: '1:291924435034:android:10da1cc06ea878d13f3863',
    messagingSenderId: '291924435034',
    projectId: 'kadike',
    storageBucket: 'kadike.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgPBhwD0KdogWf7JGXQAgcpreaa_ZE1Dk',
    appId: '1:291924435034:ios:f6e287b9bc4fb9bc3f3863',
    messagingSenderId: '291924435034',
    projectId: 'kadike',
    storageBucket: 'kadike.firebasestorage.app',
    iosBundleId: 'com.example.cardGameKe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgPBhwD0KdogWf7JGXQAgcpreaa_ZE1Dk',
    appId: '1:291924435034:ios:f6e287b9bc4fb9bc3f3863',
    messagingSenderId: '291924435034',
    projectId: 'kadike',
    storageBucket: 'kadike.firebasestorage.app',
    iosBundleId: 'com.example.cardGameKe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDteXisIvCpKJUv_2MdcnzVyXtEyjHAUHQ',
    appId: '1:291924435034:web:92e1e242d85f05cb3f3863',
    messagingSenderId: '291924435034',
    projectId: 'kadike',
    authDomain: 'kadike.firebaseapp.com',
    storageBucket: 'kadike.firebasestorage.app',
  );
}